# This is a basic workflow to help you get started with Actions

name: sample-workflow

# Controls when the workflow will run
on: [push]

jobs:
  explore-first-github-workflow:

    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
        - run: echo " The job was automatically triggered by A ${{ github.event_name}} event."
        - run: echo " This job is now running on a ${{runner.os}} server hosted by GitHub!"
        - run: echo " The name of your branch is ${{github.ref}} and your repository is {{github.repository}}."
        # Runs a set of commands using the runners shell
        - name: Check out tepository code
          uses: actions/checkout@v2
        - run: echo "The ${{github.repository}} repository has been cloned to the runner."
        - run: echo "The workflow is now ready to test your code on the runner."
        - name: List files in the repository
          run: |
            ls ${{ github.workspace}}
        - run: echo "This job's status is ${{ job.status}}."
          
        
        
